### ISSUE TITLE
help

### ISSUE THREAD

**Issue by rafix8989** [naisy/roscar#2]
hello I have a problem with starting
python joycontrol.py
pygame 2.0.1 (SDL 2.0.14, Python 2.7.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "joycontrol.py", line 10, in <module>
    from lib.rostopic import RosTopicSetter
  File "/root/roscar/lib/rostopic.py", line 1, in <module>
    rospa import
ImportError: No module named rospy

can I contact you on facebook?

**Comment by naisy** [comment]
Hi @rafix8989,
rospy is ROS1.
you can try simple examples without ros. 
```
python3 servo_test.py
python3 motor_test.py
```
